[[pages]]
path = "Chatbot.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/2_All_Tasks.py"
name = "All_Tasks"
icon = ":books:"

[[pages]]
path = "pages/6_Task_Information.py"
name = "Task_Information"

[[pages]]
path = "pages/3_Chatbot_1.py"
name = "Chatbot_1"

[[pages]]
path = "pages/4_Chatbot_2.py"
name = "Chatbot_2"

[[pages]]
path = "pages/5_Feedback.py"
name = "Feedback"
is_section=true


